spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql:///local_web_db
    username: root
    password: www.20010403.com
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis相关配置
  redis:
    host: localhost
#    host: localhost//线上
    port: 6379


server:
  port: 9999

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

logging:
  level:
    com:
      test: debug




